# Generated by Django 6.0.7 on 2026-07-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_threshold', models.FloatField(default=85.0, help_text='AI score threshold (0-100) for promoting posts to Candidates')),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Every hour'), ('6hours', 'Every 6 hours'), ('daily', 'Once daily')], default='hourly', max_length=50)),
                ('auto_shopify_integration', models.BooleanField(default=True, help_text='Auto-create Shopify products for candidates')),
                ('analysis_language', models.CharField(default='Français + Darija + Anglais', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
