# Generated by Django 6.0.7 on 2026-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='candidate_threshold',
            field=models.FloatField(default=40.0, help_text='AI score threshold (0-100) for promoting posts to Candidates'),
        ),
    ]
