"""
Django settings for oreas_server project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at project root (if present)
load_dotenv(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(+u2icmzwak#u8*muc^7-y+3l+=s4%+a(z$aisjqgzdik@l&o2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'core',
    'products',
    'instagram',
    'marketing',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Put CorsMiddleware first
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise static file serving
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # XFrameOptionsMiddleware removed: it sends X-Frame-Options: SAMEORIGIN which
    # prevents Shopify Admin from embedding this app inside its iframe.
]

ROOT_URLCONF = 'oreas_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oreas_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DB_ENGINE = os.getenv('DB_ENGINE', 'postgresql')
    if DB_ENGINE == 'sqlite':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME', 'oreas_db'),
                'USER': os.getenv('DB_USER', 'postgres'),
                'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
                'HOST': os.getenv('DB_HOST', 'localhost'),
                'PORT': os.getenv('DB_PORT', '5432'),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Shopify App Configuration
# ---------------------------------------------------------------------------
# These values come from the Shopify Partner Dashboard → App → Configuration.
SHOPIFY_API_KEY = os.getenv('SHOPIFY_API_KEY', '')
SHOPIFY_API_SECRET = os.getenv('SHOPIFY_API_SECRET', '')
SHOPIFY_APP_URL = os.getenv('SHOPIFY_APP_URL', '').rstrip('/')
SHOPIFY_STORE_URL = os.getenv('SHOPIFY_STORE_URL', '')
SHOPIFY_ACCESS_TOKEN = os.getenv('SHOPIFY_ACCESS_TOKEN', '')

# Allow iframe embedding inside Shopify Admin (admin.shopify.com / myshopify.com)
X_FRAME_OPTIONS = 'ALLOWALL'
SILENCED_SYSTEM_CHECKS = ['security.W019']


# ---------------------------------------------------------------------------
# CORS Configuration
# ---------------------------------------------------------------------------
_shopify_origins = [SHOPIFY_APP_URL] if SHOPIFY_APP_URL else []
_railway_public_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN')
if _railway_public_domain and not _railway_public_domain.startswith('http'):
    _shopify_origins.append(f"https://{_railway_public_domain}")

_local_origins = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

if DEBUG:
    # Development: allow local Vite server + public URL
    CORS_ALLOWED_ORIGINS = _local_origins + [u for u in _shopify_origins if u.startswith('http')]
    CORS_ALLOW_ALL_ORIGINS = not bool(CORS_ALLOWED_ORIGINS)
else:
    valid_origins = [u for u in _shopify_origins if u.startswith('http')]
    CORS_ALLOWED_ORIGINS = valid_origins if valid_origins else []
    CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True

# CSRF: trust requests that arrive over public domains and Shopify auth redirects
_csrf_origins_set = {'http://localhost:5173', 'http://127.0.0.1:8001', 'http://127.0.0.1:5173'}
if SHOPIFY_APP_URL and SHOPIFY_APP_URL.startswith('http'):
    _csrf_origins_set.add(SHOPIFY_APP_URL)
if _railway_public_domain:
    _csrf_origins_set.add(f"https://{_railway_public_domain}")

additional_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if additional_csrf:
    for item in additional_csrf.split(','):
        item_clean = item.strip()
        if item_clean and item_clean.startswith('http'):
            _csrf_origins_set.add(item_clean)

CSRF_TRUSTED_ORIGINS = list(_csrf_origins_set)


# Reverse proxy header configuration for SSL termination on Railway
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# DRF Config
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Celery Config
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = True  # Run tasks inline synchronously in dev mode so a separate worker is not required


# Meta / Instagram Graph API Credentials
META_CLIENT_ID = os.getenv('META_CLIENT_ID', 'your_meta_app_id_here')
META_CLIENT_SECRET = os.getenv('META_CLIENT_SECRET', 'your_meta_app_secret_here')
# Encryption key for securing tokens at rest (32-byte url-safe base64 key)
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', 'vS-d6WJ191cR2e_h7Y-hT7r46_zXg2Yt25jW6tGv_pA=')
