# Generated by Django 6.0.7 on 2026-07-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_platformsettings_candidate_threshold'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lifetime_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('optimization_goal', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_event', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaAdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_account_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ad_accounts', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='MetaAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('creative_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='marketing.metaadset')),
            ],
        ),
        migrations.CreateModel(
            name='MetaCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('objective', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='marketing.metaadaccount')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_campaigns', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='metaadset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='marketing.metacampaign'),
        ),
        migrations.CreateModel(
            name='MetaAdPerformanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('purchases_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ctr', models.FloatField(default=0.0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cpm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cost_per_result', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roas', models.FloatField(default=0.0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='marketing.metacampaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
