# Generated by Django 6.0.7 on 2026-07-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('products', '0002_product_cogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creative_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(default='VIDEO', max_length=50)),
                ('hook_type', models.CharField(blank=True, max_length=100, null=True)),
                ('has_model', models.BooleanField(default=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('editing_style', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(default='Darija', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='metaadperformanceinsight',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='metaad',
            name='creative_id',
        ),
        migrations.RemoveField(
            model_name='metacampaign',
            name='linked_product',
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='marketing.metaad'),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='confirmed_purchases',
            field=models.IntegerField(default=0, help_text='Confirmed by Call Center'),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='delivered_purchases',
            field=models.IntegerField(default=0, help_text='Delivered & Paid'),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='returned_purchases',
            field=models.IntegerField(default=0, help_text='Returned orders'),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='total_call_center_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of goods sold for delivered items', max_digits=12),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='spend + cogs + shipping + call center + returns', max_digits=12),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='total_return_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='metaadperformanceinsight',
            name='total_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='metaadperformanceinsight',
            name='purchases',
            field=models.IntegerField(default=0, help_text='Raw Shopify orders'),
        ),
        migrations.AlterField(
            model_name='metaadperformanceinsight',
            name='purchases_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Gross order value', max_digits=12),
        ),
        migrations.AlterField(
            model_name='metaadperformanceinsight',
            name='roas',
            field=models.FloatField(default=0.0, help_text='Gross ROAS (conversions / spend)'),
        ),
        migrations.AlterUniqueTogether(
            name='metaadperformanceinsight',
            unique_together={('campaign', 'ad', 'date')},
        ),
        migrations.CreateModel(
            name='MarketingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs', models.DecimalField(decimal_places=2, help_text='Product Cost of Goods Sold', max_digits=10)),
                ('call_center_cost', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=40.0, max_digits=10)),
                ('return_cost', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
                ('shopify_status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='open', max_length=50)),
                ('call_center_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered & Paid'), ('failed', 'Delivery Failed')], default='pending', max_length=50)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketing.metaad')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketing.metacampaign')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_orders', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='metaad',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='marketing.metaadcreative'),
        ),
        migrations.CreateModel(
            name='ProductTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='metacampaign',
            name='linked_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.producttest'),
        ),
    ]
