# Generated by Django 6.0.7 on 2026-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Master toggle to enable or disable Excel Online sync')),
                ('file_item_id', models.CharField(blank=True, default='', help_text='OneDrive File item_id', max_length=255)),
                ('file_name', models.CharField(blank=True, default='', help_text='Human readable file name', max_length=255)),
                ('sheet_name', models.CharField(blank=True, default='', help_text='Specific sheet name or blank for first sheet', max_length=255)),
                ('header_row', models.IntegerField(default=1, help_text='Row index containing column headers (1-based)')),
                ('unique_key_field', models.CharField(default='order_number', help_text='Order model field used for deduplication', max_length=100)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='JSON object mapping Excel headers (key) to Order model attributes (value)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_failed_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel Sync Settings',
                'verbose_name_plural': 'Excel Sync Settings',
            },
        ),
        migrations.CreateModel(
            name='OneDriveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('client_state', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
