# Generated by Django 6.0.7 on 2026-07-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelsyncsettings',
            name='auto_sync_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic background periodic fetching from share_url'),
        ),
        migrations.AddField(
            model_name='excelsyncsettings',
            name='share_url',
            field=models.URLField(blank=True, default='', help_text='OneDrive / SharePoint / Google Drive public or shared view link', max_length=1024),
        ),
        migrations.AddField(
            model_name='excelsyncsettings',
            name='sync_interval_minutes',
            field=models.IntegerField(default=10, help_text='Periodic sync interval in minutes'),
        ),
    ]
