# Generated by Django 6.0.7 on 2026-07-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_id', models.CharField(max_length=255)),
                ('facebook_page_name', models.CharField(blank=True, max_length=255)),
                ('instagram_business_account_id', models.CharField(max_length=255, unique=True)),
                ('instagram_username', models.CharField(max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_media_id', models.CharField(max_length=255, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(max_length=50)),
                ('media_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('permalink', models.URLField(max_length=1000)),
                ('posted_at', models.DateTimeField()),
                ('comments_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('is_candidate', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('comments_synced_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_error', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='instagram.instagramaccount')),
                ('linked_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_media', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_comment_id', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('asks_price', models.BooleanField(default=False)),
                ('asks_availability', models.BooleanField(default=False)),
                ('asks_color', models.BooleanField(default=False)),
                ('asks_size', models.BooleanField(default=False)),
                ('asks_delivery', models.BooleanField(default=False)),
                ('has_complaint', models.BooleanField(default=False)),
                ('detected_colors', models.JSONField(blank=True, default=list)),
                ('detected_sizes', models.JSONField(blank=True, default=list)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram.instagrammedia')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.IntegerField(default=0)),
                ('price_comments_count', models.IntegerField(default=0)),
                ('availability_comments_count', models.IntegerField(default=0)),
                ('color_comments_count', models.IntegerField(default=0)),
                ('size_comments_count', models.IntegerField(default=0)),
                ('delivery_comments_count', models.IntegerField(default=0)),
                ('negative_feedback_count', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('last_analyzed_at', models.DateTimeField(auto_now=True)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='instagram.instagrammedia')),
            ],
        ),
    ]
