# Generated by Django 6.0.7 on 2026-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_url',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='instagrammedia',
            name='permalink',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='instagrammedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
