# Generated by Django 6.0.7 on 2026-07-10 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instagram', '0002_alter_instagrammedia_media_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramCompetitorMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_media_id', models.CharField(max_length=255, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(max_length=50)),
                ('media_url', models.URLField(max_length=3000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=3000, null=True)),
                ('permalink', models.URLField(max_length=3000)),
                ('posted_at', models.DateTimeField()),
                ('like_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='instagram.instagramcompetitor')),
            ],
        ),
    ]
