# Generated by Django 6.0.7 on 2026-07-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagramcompetitor_instagramcompetitormedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcompetitormedia',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='instagramcompetitormedia',
            name='ai_score_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instagramcompetitormedia',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramcompetitormedia',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramcompetitormedia',
            name='selection_source',
            field=models.CharField(blank=True, choices=[('ai', 'AI Selected'), ('user', 'User Saved')], max_length=20, null=True),
        ),
    ]
