# Generated by Django 6.0.7 on 2026-07-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_instagramcompetitormedia_ai_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcompetitormedia',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
