# Generated by Django 6.0.7 on 2026-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Unique business identifier for the order', max_length=100, unique=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=100)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('source', models.CharField(choices=[('excel', 'Excel Online'), ('shopify', 'Shopify'), ('whatsapp', 'WhatsApp'), ('google_sheets', 'Google Sheets'), ('manual', 'Manual Entry'), ('api', 'External API')], default='excel', max_length=50)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=50)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('extra_attributes', models.JSONField(blank=True, default=dict, help_text='Stores unmapped or custom fields from the data source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='excel_online', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Failure')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_count', models.IntegerField(default=0, help_text='New orders created during sync')),
                ('updated_count', models.IntegerField(default=0, help_text='Existing orders updated during sync')),
                ('skipped_count', models.IntegerField(default=0, help_text='Orders unchanged/skipped')),
                ('failed_count', models.IntegerField(default=0, help_text='Rows that failed validation or processing')),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Diagnostic execution details')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
