# Generated by Django 6.0.7 on 2026-07-28 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='archived_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='conflict_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores local vs incoming conflicting field values'),
        ),
        migrations.AddField(
            model_name='order',
            name='has_conflict',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True if incoming sync data conflicts with manual edits'),
        ),
        migrations.AddField(
            model_name='order',
            name='imported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_manually_edited',
            field=models.BooleanField(default=False, help_text='Set to True if edited inside OREAS after last sync'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='source_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_row_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_system',
            field=models.CharField(db_index=True, default='excel_online', max_length=50),
        ),
        migrations.AddField(
            model_name='synclog',
            name='archived_count',
            field=models.IntegerField(default=0, help_text='Disappeared orders soft-deleted'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='conflict_count',
            field=models.IntegerField(default=0, help_text='Orders flagged with sync conflicts'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='validation_report',
            field=models.JSONField(blank=True, default=list, help_text='List of row validation issues'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Unmapped custom fields from source'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('excel_online', 'Excel Online'), ('shopify', 'Shopify'), ('whatsapp', 'WhatsApp'), ('google_sheets', 'Google Sheets'), ('manual', 'Manual Entry'), ('api', 'External API')], default='excel_online', max_length=50),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='failed_count',
            field=models.IntegerField(default=0, help_text='Rows failing validation'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='imported_count',
            field=models.IntegerField(default=0, help_text='New orders created'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='skipped_count',
            field=models.IntegerField(default=0, help_text='Unchanged orders skipped'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='updated_count',
            field=models.IntegerField(default=0, help_text='Existing orders updated'),
        ),
        migrations.CreateModel(
            name='OrderSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField(default=dict, help_text='Complete raw row values as imported from source')),
                ('source_row_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
                ('sync_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_histories', to='orders.synclog')),
            ],
            options={
                'verbose_name': 'Order Sync History',
                'verbose_name_plural': 'Order Sync Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
