# Generated by Django 6.0.7 on 2026-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cogs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of Goods Sold (Unit cost)', max_digits=10, null=True),
        ),
    ]
